apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: chat
  template:
    metadata:
      labels:
        tier: chat
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: web
        image: dimonum/chat:1.0-app
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: chat-db-secret
                key: db.user
          - name: DB_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: chat-db-secret
                key: db.password
          - name: DB_ADDRESS
            value: chat-db-service
