apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: chat-db
  name: chat-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: chat-db
  template:
    metadata:
      labels:
        tier: chat-db
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
      - name: db
        image: dimonum/chat-db:1.1
        ports:
            - containerPort: 3306
#        volumeMounts:
#            - name: mysql-data
#              mountPath: /var/lib/mysql
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: chat-db-secret
                key: db.user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: chat-db-secret
                key: db.password
          - name: MYSQL_DATABASE
            value: chat
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: chat-db-secret
                key: db.root.password
#      volumes:
#              - name: mysql-data
#                hostPath:
#                  path: /var/lib/mysql

